name: run

on:
  push:
  workflow_dispatch:

jobs:
  set:
    runs-on: ubuntu-24.04
    outputs:
      github: ${{ steps.set.outputs.github }}
    steps:
    - name: set
      id: set
      run: |
        echo "github<<EOF" >> $GITHUB_OUTPUT
        echo "${{ toJson(github) }}" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

  get:
    runs-on: ubuntu-24.04
    needs:
    - set
    steps:
    - name: get
      id: get
      run: |
        echo '${{ toJson(needs.set.outputs.github) }}'
