name: run

on:
  push:
  workflow_dispatch:

jobs:
  set:
    runs-on: ubuntu-24.04
    outputs:
      event: ${{ steps.set.outputs.event }}
    steps:
    - name: set
      id: set
      run: |
        echo "event<<EOF" >> $GITHUB_OUTPUT
        echo "${{ toJson(github.event) }}" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

  get:
    runs-on: ubuntu-24.04
    needs:
    - set
    steps:
    - name: get
      id: get
      run: |
        echo '${{ toJson(needs.set.outputs.event) }}'
