name: run

on:
  push:
  workflow_dispatch:

jobs:
  set:
    runs-on: ubuntu-24.04
    outputs:
      github: ${{ steps.set.outputs.github }}
    steps:
    - name: set
      id: set
      run:
        echo "::set-output github='${{ toJson(github) }}'"

  get:
    runs-on: ubuntu-24.04
    needs:
    - set
    steps:
    - name: get
      id: get
      run:
        echo "$(echo ${{ fromJson(needs.set.outputs.github) }} | jq .job)"
